{
 "title": "Docker Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(docker_container_info{compose_project=~\"$compose_project\"},name)"
    }
   },
   {
    "name": "compose_project",
    "label": "Instance",
    "query": {
     "query": "label_values(docker_container_info,compose_project)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_container_memory_usage_bytes{name=~\"$container\", compose_project=~\"$compose_project\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(docker_container_cpu_seconds_total{name=~\"$container\", compose_project=~\"$compose_project\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PIDs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "docker_container_pids{name=~\"$container\", compose_project=~\"$compose_project\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block IO",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(docker_container_blkio_read_bytes_total{name=~\"$container\", compose_project=~\"$compose_project\"}[$__rate_interval])",
     "legendFormat": "{{name}} read"
    },
    {
     "expr": "rate(docker_container_blkio_write_bytes_total{name=~\"$container\", compose_project=~\"$compose_project\"}[$__rate_interval])",
     "legendFormat": "{{name}} write"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(docker_container_network_rx_bytes_total{name=~\"$container\", compose_project=~\"$compose_project\"}[$__rate_interval])",
     "legendFormat": "{{name}} read"
    },
    {
     "expr": "rate(docker_container_network_tx_bytes_total{name=~\"$container\", compose_project=~\"$compose_project\"}[$__rate_interval])",
     "legendFormat": "{{name}} write"
    }
   ]
  }
 ]
}